language: java
matrix:
  include:
    - os: osx
      osx_image: xcode9.3
before_install:
    - wget "https://drive.google.com/uc?export=download&id=1LvKEwVt_JdgrozigXXMwm0bvedGfIxM1" -O netty-tcnative-boringssl-static-2.0.29.Final-SNAPSHOT.jar
    - mvn install:install-file -Dfile=netty-tcnative-boringssl-static-2.0.29.Final-SNAPSHOT.jar
